### ISSUE TITLE
Reproducing the Gabbard animation

### ISSUE THREAD

**Issue by s-m-e** [mads-hatters/SIADS-591-Orbital-Congestion#23]
@timzai Hi, thanks for this excellent repo! I have been looking at your [animation code](https://github.com/mads-hatters/SIADS-591-Orbital-Congestion/blob/main/job/gabbard/animated_gabbard.ipynb). It's referencing some obviously preprocessed data in `input_file_path = '../../../siads591 data/processed_data/gabbard/gabbard_36H40.pkl'`. I am somehow failing to locate where across this repo this particular file originates or is being created. Its path points to somewhere above / outside the git repo. How could I reproduce it or how could I reproduce the animation?

---

Context: I am constantly on the look for interesting animated scientific visualizations. I am developing a [Python package called `bewegung`](https://bewegung.readthedocs.io) for exactly this purpose. Your data (as seen through your animation) contains so many interesting features that I'd like to look into potentially taking the animation a few steps further.

**Comment by cassova** [comment]
@s-m-e The data used to create the visuals is from all `gp_history` available from Space-Track.org.  This is a massive dataset, too large for github.  This is why it's not available in our repository.  If you wish, you can aquire the same data from Space-Track.org using a free account but be warned that API limitations make this data gathering time consuming.

**Comment by timzai** [comment]
Hi @s-m-e like @cassova said, the size of the data is too big to be put on github.  You can find the data download and processing code in the `/job/space_track` directory.  Look at these files specifically:

- `download_all_gp_history.ipynb`
- `filter_raw_data_gabbard.ipynb`
- `process_gabbard_data_interpolated.ipynb`

You do need a space-track.org account and I think the number of API calls needed are around 1500 at the moment

**Comment by s-m-e** [comment]
@cassova & @timzai Thanks for the feedback :) I simply missed `process_gabbard_data_interpolated.ipynb`. It's this file where `gabbard_36H40.pkl` is assembled. For some stupid reason, a full-text search for `gabbard_36H40.pkl` did not reveal those relevant lines.

Yeah, your query against `space-track.org` will take a while. Just to be on the safe side: What order of magnitude of disk space will I need for this?

**Comment by timzai** [comment]
@s-m-e its around 80GB total raw, a bit less than 20 if you compressed them with gzip

**Comment by timzai** [comment]
@s-m-e also watch out for their API limit if you have fast internet.

**Comment by s-m-e** [comment]
@timzai That's 80GB of both, required storage *and* internet traffic, right? I live in Germany - fast internet is definitely not a thing around here :/ I can not see API limits with respect to bandwidth, [only with respect to number of queries per unit of time](https://www.space-track.org/documentation#/api): "Limit API queries to less than 30 requests per minute / 300 requests per hour". Do I correctly understand that your code does not fall under any of the special categories listed below (CDM, TLE, ...)?

**Comment by timzai** [comment]
There's no bandwidth limit, just frequency.

When I downloaded it It was about 40 seconds per file, so I wasn't anywhere close to reaching the API limit.

I don't think `gp_history` falls under any of the listed category, `gp` might fall under `TLE` though

**Comment by timzai** [comment]
@s-m-e let me know to close this if everything is OK

**Comment by cassova** [comment]
Closing issue since no further activity.  Feel free to open another if any additional questions.
